# Generated by Django 6.0.4 on 2026-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('problem', models.CharField(max_length=200)),
                ('doctor', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
            ],
        ),
    ]
