# Generated by Django 6.0.4 on 2026-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='about',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
