# Generated by Django 6.0.4 on 2026-04-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_doctors_about_doctors_available_doctors_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
