# Generated by Django 6.0.2 on 2026-04-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_doctors_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
