# Generated by Django 6.0.2 on 2026-04-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_alter_doctors_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
